version: '3.6'
services:
  mail:
    image: mailhog/mailhog:latest
    ports:
     - 58002:8025
  db_pma:
    depends_on:
     - db
    image: phpmyadmin/phpmyadmin:latest
    ports:
     - 58001:80
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: f8s9798739848789sd6
  db:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: wp_generator
      MYSQL_ROOT_PASSWORD: f8s9798739848789sd6
    volumes:
    - "./docker/mysql:/docker-entrypoint-initdb.d"
  www:
    depends_on:
    - db
    build:
      context: ./docker
      dockerfile: Dockerfile
    volumes:
    - "./src:/var/www/html"
    environment:
      GN_DOMAIN: localhost:58000
      DB_HOST: db
      DB_DATABASE: wp_generator
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: f8s9798739848789sd6
      MAIL_ON: 1
      MAIL_ADDR: mailer@example.com
      MAIL_SMTP: mail
      MAIL_PORT: 1025
    ports:
    - 58000:80
